baseURL = "https://powertrader.es/" 
languageCode = "es-es"
title = " "
theme = "PaperMod"

[params]
    env = "production"
    description = "Inteligencia Energética y Mercados"
    author = "PowerTrader"
    defaultTheme = "dark"
    images = ["/social_profile.png"]
    

    [params.profileMode]
        enabled = true
        title = ""
        subtitle = "Inteligencia Artificial aplicada al Mercado Energético"
        imageUrl = "/social_profile_transparente.svg" # Asegúrate de poner el nombre exacto de tu archivo de la carpeta static/
        imageTitle = "PowerTrader Logo"
        imageWidth = 900 # Como tu logo es alargado, ponle más anchura
        # imageHeight = 120 <-- BORRA esta línea para que no te aplaste el logo y mantenga su proporción original
        imageHeight = 360

        [[params.profileMode.buttons]]
          name = "EnergyFlash (Informe Diario)"
          url = "https://energyflash.powertrader.es" 

        [[params.profileMode.buttons]]
          name = "PowerRadar (Informe Semanal)"
          url = "https://powerradar.powertrader.es"

        [[params.profileMode.buttons]]
          name = "EnergyVision (Informe Mensual)"
          url = "https://energyvision.powertrader.es"

        [[params.profileMode.buttons]]
          name = "PowerAhorro (Consejos de ahorro)"
          url = "https://powerahorro.powertrader.es"

        [[params.profileMode.buttons]]
          name = "EnergyTech (Autoconsumo y Baterías)"
          url = "https://energytech.powertrader.es"

        [[params.profileMode.buttons]]
          name = "ProductorSolar (Plantas Fotovoltaicas)"
          url = "https://productorsolar.powertrader.es"

[params.assets]
    disableHLJS = true
    favicon = "/favicon.svg"
    safari_pinned_tab = "/favicon.svg"

[params.label]
    text = "" # Este es el texto que saldrá al lado del logo
    icon = "/logo_transparente.svg" # Ruta a tu archivo en la carpeta static/
    iconHeight = 60 # Tamaño del logo en píxeles (30-35 es ideal para que quede elegante)
    
[markup.goldmark.renderer]
unsafe = true

[sitemap]
  changefreq = "daily"
  priority = 0.8
  filename = "sitemap.xml"
